### ISSUE TITLE
Remove CLI update command 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#107]
The `invenio-cli update` command is only needed in the local development workflow, because static files are not symlinked. If we follow the same apporach as for the `assets/` folder's symlinking, we should be able to remove the need for that command and make the whole development experience seamless.

**Comment by ppanero** [comment]
So they would be symlinked upon "install" (previous `build --local`)?

**Comment by fenekku** [comment]
Yes they would, but like every idea after a night's rest, we may not be able to get rid of it in the end...

Symlinking is done on a per file basis actually (thought it was on the folder originally), so adding new files will require the update command. I will document this too. I am closing this though.
