### ISSUE TITLE
destroy command

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-cli#120]
Returns TODO: Revisit destroy command

**Comment by ppanero** [comment]
Thanks Tom!

We were rethinking if it was useful and if so how to do it. Sorry for the no user friendly message 😅 It should say something like "Not supported yet".

Added it to the planning to work on it soon :)

**Comment by lnielsen** [comment]
From some experience, the destroy command should:

- stop and remove docker containers
- ``pipenv --rm`` to remove the virtualenvironment

**Comment by ppanero** [comment]
`pipenv --rm` needs further testing. What happens if you are in an already activated env. Does it destroy it too?
