### ISSUE TITLE
cli not creating logs

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#126]
The creation of the `DockerHelper` objects do not get pased a `LogginConfig` object. Therefore the logs are not piped to `/logs/invenio-cli.log`.

**Comment by fenekku** [comment]
Right. I've relied on using `docker logs` instead. Given that, I don't know how important this task would be to be honest.

**Comment by ppanero** [comment]
Well, I think users were using the logs file, at least it was useful to see when something went wrong. I would personally like to have it. Let's keep as is, but with this issue open to re-think in the future how to do the logging.

**Comment by fenekku** [comment]
Ok :)

**Comment by ppanero** [comment]
closed in favour of #48
