### ISSUE TITLE
docs: create end use docs

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#13]
Document the usage of the CLI to deploy and customize an RDM instance as of the specified Roadmap.

**Comment by ppanero** [comment]
Created a Wiki page in `invenio-app-rdm` link [here](https://github.com/inveniosoftware/invenio-app-rdm/wiki)

**Comment by ppanero** [comment]
The Wiki is created. However, until the documentation tools is chosen and deployed this is **blocked** (on https://github.com/inveniosoftware/invenio-app-rdm/issues/21)

**Comment by fenekku** [comment]
I have reviewed the wiki in its entirety, tested it out on 2 environments and made edits to the text. It is good to go :+1: for me.

Environments tested:

|                | Ubuntu 18.04              | RHEL 7.7 (Maipo)             |
| -------------- | ------------------------- | ---------------------------- |
| python         | 3.6.8                     | 3.6.8                        |
| pipenv         | 2018.11.26                | 2018.11.26                   |
| nodejs         | v8.16.2                   | v10.16.3                     |
| npm            | 6.4.1                     | 6.9.0                        |
| docker         | 19.03.4, build 9013bf583a | 1.13.1, build 7f2769b/1.13.1 |
| docker-compose | 1.24.0, build 0aa59064    | 1.22.0, build f46880fe       |
| elasticsearch  | 6.8.2                     | 7.2.0                        |
| postgresql     | 9.6                       | 9.6                          |

The one issue I ran into was not having a C compiler, python headers and nodejs+npm installed on the computer first. I've indicated that those need to be installed in development mode prior to running the commands in the wiki. It's all set. I like how the wiki is written, it's fun.
