### ISSUE TITLE
Avoid usage of ".invenio.private" when possible

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-cli#130]
Storing values in `.invenio.private` should be avoided whenever possible. The location of the `.invenio` file is usually enough to be able to compute all the necessary values at the beginning of running the `invenio-cli` command (similar to how `pipenv` treats the `Pipfile` as a point of reference):

- `project_dir`: this is the absolute path of the `.invenio` file
- `instance_path`: Since `.invenio` is in the same directory as the `Pipfile`, using `pipenv --venv` would return the absolute virtualenv path (even in the case that one was already created and activated from before). We can then append `var/instance` to this value

Note: this is not meant to be a full removal of `.invenio.private`, which should be still be used for hardcoding values. The incentive is to minimize local state/files that need to be gitignore'd and to provide sane defaults for users of the CLI.

**Comment by fenekku** [comment]
Preach it (and I am the one who probably stored `project_dir` and `instance_path` in it). The selling use case for this issue is: make team development on an instance easy.

As part of a team I want to clone the instance repository and run `invenio-cli install` ... without having to artifically create a `.invenio.private` with a path to a virtualenv that I didn't create yet (because invenio-cli install should create it).

`.invenio.private` could still be used to cache those values, but if it doesn't exist, it shouldn't block installation (and then it should be created).

**Comment by chbrandt** [comment]
Ok... So maybe I have my workflow wrong. @lnielsen let me know what is wrong in the following, please.

## My devel-workflow
1. After I created my InvenioRDM project (eg, `my_site`) I also created a new Git repository with all the content (includsing `.gitignore`) inside my project's directory
2. I then proceeded to do my customization, tests, etc. When I got satisfied I pushed everything (but my secrets file, which now are also inside `.gitignore`) to a private repo on Github.
3. I then go to another machine to test the containers deployment:
  * [git-clone] In the "other" machine and clone my project repository ("my_site")
  * [cli-install] Then I install `invenio-cli` using `pipenv`
  * [containers-build] And finally I try to `invenio-cli containers start --lock --build --setup`
    But when I do that, it complains:
    > ```
    > Error: Missing '.invenio.private' file in current directory. Are you in the project folder?
    > ```

## Note on `.invenio.private`
The `.invenio.private` is created when we _init_ a project (`invenio-cli init rdm`), and included in the project's `.gitignore`:
> ```
> # Invenio-cli per machine file
> .invenio.private
> ```

A fresh `.invenio.private` looks as follows:
```
[cli]
project_dir = /some/path/to/inveniordm/my_site
instance_path = 
services_setup = False
```

## My work-around
Maybe there is an `invenio-cli` command that creates a new `.invenio.private` file with this machine/environment, but I don't (yet) know about.

What I did was to create a new, blank project (`invenio-cli init rdm`) to have the `.invenio.private` above. I then copied it to my _cloned_ repo, updated `project_dir` accordingly and `invenio-cli containers start --lock --build --setup`. 

After the containers are build-start, `.invenio.private` changes slightly:
```diff
[cli]
project_dir = /home/chbrandt/tmp/test_clone/inveniordm_project
instance_path = 
- services_setup = False
+ services_setup = True
```

And that's it, things are working. But I had to create `.invenio.private` manually.

**Comment by fenekku** [comment]
@chbrandt `.invenio.private` currently does require more steps to get team workflow going (or even just like you have, a multiple repo setup). Manually creating that file like you did is what you have to do in those cases. Here is the documentation I made for my colleagues as part of the installation process:

---

Create a virtualenv using [pipenv](https://pipenv.pypa.io) and Python 3.7:

    pipenv run python -c 'print("pipenv virtualenv created")'

Fill out the `.invenio.private` file locally with values specific to your filesystem:

```ini
# .invenio.private
[cli]
project_dir = /<path>/<to>/<dir containing this file>
instance_path = /<path>/<to>/<created virtualenv>/var/instance
services_setup = False
```

The created virtualenv's path can be obtained via `pipenv --venv`.
 
---

It wouldn't be too hard to modify the code to make `.invenio.private` non-required and just a cache. PR welcomed!
