### ISSUE TITLE
celery worker not starting

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#160]
Package version (if known): 0.17.1

## Steps to Reproduce
1. run `invenio-cli run`
2. See error in the console:
```
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: no such option: --app
```

## Expected behavior

Celery worker to be up and running

**Comment by jhrdt** [comment]
Hej,

I had the same issue lately.
If you use the latest celery version (5.0.0), the order of the cli arguments changed.

See PR #161

**Comment by ppanero** [comment]
@wgresshoff reported this happening again in v0.17.2

**Comment by ppanero** [comment]
delegated to helm chart, local and containerize are working
