### ISSUE TITLE
Celery docker instance started with invenio-cli containerize --pre keeps restarting for "no such option: -A"

### ISSUE THREAD

**Issue by origliante** [inveniosoftware/invenio-cli#171]
Package version: invenio-cli 0.17.2

## Describe the bug
Celery docker instance created on macOS with "invenio-cli containerize --pre" does not start and in the logs you have:
```
You are using `-A` as an option of the worker sub-command:
celery worker -A celeryapp <...>

The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp worker <...>
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: no such option: -A
```

## Steps to Reproduce
1. on macOS, init preview env with python 3.7 and postgres (other combinations untested)
2. start containers with "invenio-cli containerize --pre"
3. check docker ps and Celery logs

## Expected behavior
Celery to correctly start (or scripts to pick correct version)

**Comment by cenouralm** [comment]
After reproducing these steps I got the same behavior as described. 
Log from `docker ps` shows:
`6c6a5485a5a3        my-site                                                   "bash -c 'celery wor…"   2 hours ago         Restarting (2) 21 seconds ago`

Log from the container:
celery worker -A celeryapp <...>

The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp worker <...>
Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: no such option: -A
You are using `-A` as an option of the worker sub-command:
celery worker -A celeryapp <...>

**Comment by lnielsen** [comment]
So it's fixed in the master branch of [cookiecutter-invenio-rdm](https://github.com/inveniosoftware/cookiecutter-invenio-rdm/commit/b073c605962a3acbdb0c0252ad70fdde5e55fac3). It will be available in the upcoming October release.
