### ISSUE TITLE
--help prevented by need to be in folder with .invenio

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#184]
Package version (if known): november release (master prior to it)

## Describe the bug
I suspect that @pass_cli_config, prevents `--help` of many commands to be executed unless the present working directory is an invenio instance. Output is:

```
Error: Missing '.invenio' file in current directory. Are you in the project folder? 
```

instead of help messages.

## Expected behavior

It should be possible to consult the `--help` of any command without being in the directory where the `.invenio` file is. (at least that's my vote)

**Comment by lnielsen** [comment]
Just some extra info. The general help works (e.g. ``invenio-cli --help``) however the subcommands doesn't work:

```
% invenio-cli assets --help                                                                                                                                                                     @master
Usage: invenio-cli [OPTIONS] COMMAND [ARGS]...

Error: Missing '.invenio' file in current directory. Are you in the project folder?
```
