### ISSUE TITLE
Would like not to have to run invenio-cli packages lock before install

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#198]
Package version (if known): november release

Documentation was missing about this (fixed in submitted PR): installing person needs to run `invenio-cli packages lock` before being able to run `invenio-cli install`. Ideally, `invenio-cli install` would just take care of things (re-introducing `--skip-lock` if want to do other install steps but not re-fetch-lock could be possible). 

Actually ran into this while upgrading: I changed my dependencies in my Pipfile and ran `invenio-cli install` like last time, but my changes to Pipfile were not taken into account. Not the ideal experience. My take is that we should limit the number and verbosity of commands installing people have to run.  

(It's tricky to understand the intention with the skipped tests...)

**Comment by lnielsen** [comment]
After some discussion, let's go with:

```
# First time bootstrapping an InvenioRDM instance.
invenio-cli init rdm
cd my-site
# install detects that no Pipfile.lock exists, and runs "packages lock" 
invenio-cli install
```

```
# Instance has already been bootstrap.
cd my-site
# install detects Pipfile.lock exists, and will not run "packages lock"
invenio-cli install
```

This makes it simpler to get started with a new instance. The package mangement (i.e. upgrading PyPI packages) should happen as an consicuous thing - i.e. it shouldn't be run as part of install. Instead it should could be part of some upgrade command. Install should just install what the lock file says.
