### ISSUE TITLE
fix typo in error message

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#208]
https://github.com/inveniosoftware/invenio-cli/blob/3258c3731f792595b61807f4297ea71814d9a068/invenio_cli/commands/assets.py#L66

`link-dis` should be `link-dist`

**Comment by Siddharth1010** [comment]
@ppanero Hey could you assign this to me?

**Comment by ppanero** [comment]
@Siddharth1010 done, moved to in progreess. Feel free to put me as reviewer for the merge :)

**Comment by Siddharth1010** [comment]
@ppanero I have fixed the typo and created a PR. Let me know if I need to change anything :)
