### ISSUE TITLE
install --dev should install dev dependencies

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#213]
Package version (if known): commit/b0cee31b1ec1a41e14e3e54c08edd6d20932896f

## Describe the bug
Running `invenio-cli install --dev` should install dev dependencies. Note: `--dev` may change name eventually (see #199).
dev dependencies are locked but not installed.

## Expected behavior
dev dependencies are installed.

**Comment by ppanero** [comment]
`--dev` gets passed all the way from `install` command till the `lock`, which adds them to the Pipfile (ant then get installed...). What is the exact issue?

**Comment by fenekku** [comment]
They don't get installed. `pipenv sync --dev` is needed to install dev dependencies, but we are calling `pipenv sync` or `pipenv sync --pre`. At least that's what the pipenv docs imply and what I had happened before (maybe they changed it recently, but I could try to reproduce eventually).

**Comment by ppanero** [comment]
Tested it with the dependency that is by default in dev of the Pipfile (check-manifest)... you are correct.

```
invenio-cli init
invenio-cli install --pre
pip freeze | grep check
# Nothing shown
```

```
invenio-cli init
invenio-cli install --pre --dev
pip freeze | grep check
# Nothing shown
```

I assumed `sync` would get what was on the Pipfile (where check-manifest is present...)

**Comment by ppanero** [comment]
@fenekku can this be a help wanted? is fairly self contained to be done by external?

**Comment by fenekku** [comment]
Marking it "help wanted" is a good idea. It's indeed really small.

**Comment by ppanero** [comment]
Perfect, added the tag. Not moving from the board until it has passed triage as we agreed last planning session :)
