### ISSUE TITLE
Possible missing dependency during installation

### ISSUE THREAD

**Issue by jrief** [inveniosoftware/invenio-cli#222]
Package version (if known): 0.22.0

## Describe the bug

I try to install Invenio following the instruction step by step as described in the main README under **Local Development environment**, but this raises an error.

## Steps to Reproduce

```
$ invenio-cli install --pre
Locking python dependencies...
Locking [dev-packages] dependencies...
Building requirements...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
✔ Success! 
Updated Pipfile.lock (b6cd98)!
Installing python dependencies... Please be patient, this operation might take some time...
Installing dependencies from Pipfile.lock (b6cd98)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
All dependencies are now up-to-date!
Updating instance path...
Failed to install dependencies.
Errors: Traceback (most recent call last):
  (... snip ...)
  File "xxx/lib/python3.7/site-packages/invenio_records_resources/resources/record_config.py", line 14, in <module>
    from flask_resources.parsers import ArgsParser
ImportError: cannot import name 'ArgsParser' from 'flask_resources.parsers' (xxx/lib/python3.7/site-packages/flask_resources/parsers/__init__.py)
```

## Expected behavior

It shall run without errors.

**Comment by avivace** [comment]
Thanks for the report, @jrief. I can't seem to reproduce this.

Can you retry with the new version of `invenio-cli` (0.23.0)?

**Comment by fenekku** [comment]
Both flask-resources and records-resources have changed and this is not applicable anymore. If a similar issue arises with the new versions, let us know by filing another ticket. Thanks!
