### ISSUE TITLE
Remove sqlite references

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#231]
Now that sqlite is not a supported DB for InvenioRDM, let's remove references to it in this repo.

**Comment by avivace** [comment]
@fenekku What can we use in this mock https://github.com/inveniosoftware/invenio-cli/blob/8d49e09e1948c78ea7efe38bfc92198d732b7560/tests/commands/conftest.py#L40 ?

**Comment by fenekku** [comment]
We can use "postgresql".
