### ISSUE TITLE
check-requirements: add imagemagick

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#247]
**Description**
`ImageMagick` is needed to perform some tasks for files and IIIF (e.g. width and heigth extraction).

Since it is a system package and its installation depends on the OS, it can be checked in the same fashion than in the processors [here](https://github.com/inveniosoftware/invenio-records-resources/blob/c6c26a8fc6acc0b4aadd1bf894a2ff9c4d6e61d7/invenio_records_resources/services/files/processors/image.py#L18).

Goal: add a new step [here](https://github.com/inveniosoftware/invenio-cli/blob/master/invenio_cli/commands/requirements.py#L156) which checks it's existence. Note that the containerized version will need this https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/159 to be solved.

It is only needed for:
- IIIF
- File metadata extraction

So it might not be a "hard" failure if not found but sort of a warning instead?

**Comment by Pineirin** [comment]
The command to check the version of ImageMagick behaves differently in CentOS, we need to explore other options to make the command work in different platforms.
