### ISSUE TITLE
invenio-cli: warning doesn't work in ProcessResponse.

### ISSUE THREAD

**Issue by Pineirin** [inveniosoftware/invenio-cli#249]
The [ProcessResponse](https://github.com/inveniosoftware/invenio-cli/blob/master/invenio_cli/helpers/process.py) class in invenio-cli takes warning as a parameter, but it never uses it, neither to show the desired response as a warning, neither for anything else.
As far a I understand, it should allow to show the desired response as a warning instead of as an error or at least it should have some functionality bound to it.

**Comment by fenekku** [comment]
The warning parameter is used to assign the`self.warning` variable and is used here: `https://github.com/inveniosoftware/invenio-cli/blob/c5de2296c5f8920fe26274ec2f6963030fb604e7/invenio_cli/cli/utils.py#L31` to determine how to output the error message i.e. there is no issue.
