### ISSUE TITLE
global: pipenv courtesy notices

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#51]
Is it possible to avoid courtesy notices from pipenv?

**Comment by fenekku** [comment]
Why yes there is: setting the following environment variable `PIPENV_VERBOSITY=-1`

**Comment by ppanero** [comment]
@fenekku It was feedback given by the partners. Not sure disabling full verbosity is good. Thats why I opened this :)

**Comment by ppanero** [comment]
Fixed by setting the environment of the subprocess calls.
