### ISSUE TITLE
flask commands disambiguation

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#56]
Flask commands from `invenio` get shown when using `invenio-cli --help`.

**Comment by fenekku** [comment]
How peculiar! Where does this happen? Definitely not intended, buuuuut actually could be helpful in the sense that it would mean the modules' commands are directly accessible (no need for subprocess)?

**Comment by fenekku** [comment]
This is probably because virtualenvs are mixing streams. This is causing some weird issues like

`invenio-cli assets --local` just not collecting and building assets but running `invenio collect` and `invenio webpack` separately in the right virtualenv on the command line does work.

**Comment by ppanero** [comment]
After the latest release also the `assets` command gets overwitten by `invenio-assets` one.
