### ISSUE TITLE
server --local should run in Flask development mode

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#67]
The environment variable: `export FLASK_ENV=development` should be set somehow when running `server --local`. This allows the debugger and other niceties to be there for developers.

**Comment by ppanero** [comment]
Shall we do something like ``os.environ["FLASK_ENV"] = "development"`` in the code? Only if `verbose`?

**Comment by fenekku** [comment]
Yes `os.environ["FLASK_ENV"] = "development"` should do the trick since the child processes will inherit it. I would only set it in `--dev` though and keep `--verbose` just for terminal output.
