### ISSUE TITLE
init: support different profiles

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#8]
Inside the RDM flavour, support the creation of the repository according to different profiles:
- [ ] BioMed Repository
- [ ] Generic Repository

**Comment by fenekku** [comment]
Dependent on https://github.com/inveniosoftware/invenio-rdm-records/issues/5 to allow resource type customization. Resource type customization is one of the main customizations that depends on the profile.

**Comment by lnielsen** [comment]
Closing as we have currently gone away from the idea of the profiles.
