### ISSUE TITLE
keep custom templates in sync with local / containers environment

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#81]
Custom templates must somehow find their way in `<instance path>/templates/` . 

For `--local` environment, 2 potential avenues:
- copying
- symlink <---- Chosen

For `--containers` just copy the folder at image creation. (in view of new workflow)

Part of https://github.com/inveniosoftware/invenio-app-rdm/issues/6

**Comment by ppanero** [comment]
For easiness of updated and since we are already symlinking the cfg file (see https://github.com/inveniosoftware/invenio-cli/blob/520ad9a7457c5a4e7c081a07e2960d3b1779ab01/invenio_cli/helpers/scripts.py#L140) I would vote for symlinking.
