### ISSUE TITLE
print invenio-cli version with invenio-cli --version

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#82]
RIght now `invenio-cli --version` prints

```
Python 3.6.8
Flask 1.1.1
Werkzeug 0.16.0
```

It should print:

```
invenio-cli <version> 
```

**Comment by ppanero** [comment]
This is currently falling back to `invenio --version` due to the command inclusion (see https://github.com/inveniosoftware/invenio-cli/issues/56).

I would say that when re-writting this for the issue above, it should be changed for its own (i.e. print the invenio-cli version only).

WDYT?

**Comment by fenekku** [comment]
Sure: invenio-cli version only (edited above to reflect that)
