### ISSUE TITLE
Installing invenio-cli through pipenv breaks --local commands

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-cli#83]
Easier to explain by listing the reproducing factors and then detailing what is happening:

Steps to reproduce:

1- install invenio-cli in a virtualenv and activate it
2- `(virtualenv)$ invenio-cli init --flavour=RDM --local`
3- `cd <project>`
4- `(virtualenv)$ invenio-cli build --pre --local`  (now have Pipfile and Pipfile.lock for the instance venv)
5- `(virtualenv)$ invenio-cli assets --local`
Expect:
6- assets to be collected and built
Get:
6- no assets collected or built

Running `(virtualenv)$ pipenv run invenio collect` and `(virtualenv)$ pipenv run invenio webpack buildall` does work.

This applies to any of the `--local` commands. 

~~My theory is it's because the created application (`create_cli`) is from the invenio-cli virtualenv context rather than the instance virtualenv context so none of the config is setup and there the commands are not operating on the right targets.~~

Core of the problem is that invenio-cli and the instance's installed dependencies are in different virtualenvs. This happens even if `PIPENV_IGNORE_VIRTUALENVS` is NOT set, because pipenv associates a Pipfile to a virtualenv: installing invenio-cli with pipenv will create a Pipfile that is different than the Pipfile `invenio-cli init` creates, so pipenv creates a new virtualenv to match *that* Pipfile everytime.

**WORKAROUND**
(extracted from comment below)

Say you have already installed invenio-cli through pipenv:

1- Run the init command to get the project laid out: `pipenv run invenio-cli init --flavour=RDM`
2- `cd <project folder>`
3- Install invenio-cli as part of the new Pipfile: pipenv install invenio-cli (check that it is there in the generated Pipfile)
4- Run the rest of the `invenio-cli --local` commands starting with: `pipenv run invenio-cli build --local --pre`

Because of this song and dance, we recommend these instructions for developing locally: https://github.com/ppanero/invenio-rdm-extension-demo/wiki

**Comment by ppanero** [comment]
`invenio-cli` was installed using `pipenv`. In order to work with it, these are the steps:

``` console
USER:   pipenv install --pre ../../../inveniosw/invenio-cli/

INIT:   pipenv --rm
        rm Pipfile
        rm Pipfile.lock
        exit
        cwd my-site/
        pipenv install --pre ../../../invenio-cli
        pipenv shell
        

USER:   cd my-site/
        invenio-cli build --pre --local --verbose

BUILD:  ...
```

Note that the commands are put with a tag at the beginning. That is for clarity of implementation, in case we go this way.
