### ISSUE TITLE
working with `invenio` command in a container env

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#85]
When deploying a container environment accessing invenio management CLI is not trivial. For example in order to create users, add roles/permissions to them, etc.

One possible solution is to create some sort of "forwarding" between the `invenio-cli` and the container.

**Comment by fenekku** [comment]
Could we just document that: `docker exec -it <container_name> /bin/bash` will allow developers to get inside the container and run their commands from there?

**Comment by ppanero** [comment]
@fenekku I agree on that. Plus if they really need it is for development, in which case they do not need to `docker exec` since its locally installed. This issue came up in previous releases (e.g. to create an admin user, if we provide that - docs - it should be fine)

**Comment by fenekku** [comment]
Good. I will provide that documentation in the documentation I will write today and close this then.
