### ISSUE TITLE
setup: location should be configurable

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-cli#96]
`invenio-cli` creates a default location on local storage. However if the S3 extension is configured it should change the location creation to be on the S3 volume.

(Includes conclusions from discussion below)

**Comment by fenekku** [comment]
@ppanero This can be closed, right? Files are uploaded on S3 correctly, so the location has been changed.

**Comment by ppanero** [comment]
Hmmm my thought was more that when `setup` in invenio-cli, I mean when all the services commands are called the location is created to the local FS. If S3 was chosen there is no need for that and maybe we could call directly the correct one in the CLI. However, it's documented how to do it (pipenv....) in the extensions section. So I would still like this but as extreme backlog, not priority at all. WDYT?

**Comment by egabancho** [comment]
Would something like this work for you guys?

```diff
modified   invenio_cli/commands/services.py
@@ -91,6 +91,15 @@ class ServicesCommands(Commands):
 
         return steps
 
+    def _deafult_location_path(self):
+        """Build default location path based on file storage selection."""
+        file_storage = self.cli_config.get_file_storage()
+        if file_storage == 'local':
+            return '{}/data'.format(self.cli_config.get_instance_path())
+        return '{}://default'.format(
+            self.cli.config.get_file_storage().lower()
+        )
+
     def _setup(self):
         """Services initialization steps."""
         steps = [
@@ -107,7 +116,7 @@ class ServicesCommands(Commands):
             CommandStep(
                 cmd=['pipenv', 'run', 'invenio', 'files', 'location',
                      'create', '--default', 'default-location',
-                     "{}/data".format(self.cli_config.get_instance_path())],
+                     self._deafult_location_path()],
                 env={'PIPENV_VERBOSITY': "-1"},
                 message="Creating files location..."
             ),
modified   invenio_cli/helpers/cli_config.py
@@ -108,6 +108,10 @@ class CLIConfig(object):
         """Returns the database type (mysql, postgresql)."""
         return self.config[CLIConfig.COOKIECUTTER_SECTION]['database']
 
+    def get_file_storage(self):
+        """Returns the file storage (local, s3, etc.)."""
+        return self.config[CLIConfig.COOKIECUTTER_SECTION]['file_storage']
+
     @classmethod
     def write(cls, project_dir, flavour, replay, instance_path=None):
         """Write invenio-cli config file.
```

**Comment by ppanero** [comment]
@egabancho LGTM! I guess the resulting `s3://default` is the `data/default-bucket` you mentioned in https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/53 ?

Could you add the issues related to this matter to `May QA` sprint board? or request me review so we try review and merge?

**Comment by egabancho** [comment]
> I guess the resulting s3://default is the data/default-bucket you mentioned in inveniosoftware/cookiecutter-invenio-rdm#53 ?

Yes, it is. I changed the path because not all file systems have the concept of buckets, AFAIK EOS doesn't.

Ideally, I think the responsibility of creating the default location should be delegated to the storage class, but I didn't want to go down this path just for this, i.e. letting other extensions/modules extend (somehow) invenio-cli.
